/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rejtjelezo;

import java.util.regex.Pattern;

/**
 *
 * @author debto
 */
public class RejtjelezoFrame extends javax.swing.JFrame {

    private static String abc = "aAáÁbBcCdDeEéÉfFgGhHiIíÍjJkKlLmMnNoOóÓöÖőŐpPqQrRsStTuUúÚüÜűŰvVwWxXyYzZ";
    private static String[][] tabulaRecta = tabulaRectaGeneralas();
    private static String vizsgalatEredmeny;
    private static String kulcs;
    private static String nyers;
    
    private static String[][] tabulaRectaGeneralas(){
        
        String[][] tomb = new String[70][70];
        for (int i = 0; i < 70; i++) {
          tomb[i] = abc.split("");
          String veg = abc.substring(0, 1);
          String kezdo = abc.substring(1, 70);
          abc = kezdo.concat(veg);
        }
        
        return tomb;
        
    }
    
    private static String[] kulcsSzovegHosszuvaTetele(String nyers, String kulcs){
        String[] splitNyersSzoveg = nyers.split("");
        String[] splitKulcs = kulcs.split("");
        String[] KulcsNyersHosszuva = new String[splitNyersSzoveg.length];
        
        int i;
        int j = 0;
        for(i = 0; i < splitNyersSzoveg.length; i++){
            KulcsNyersHosszuva[i] = splitKulcs[j];
            if(j < splitKulcs.length-1){
                j++;
            }else{
                j = 0;
            }
        }
        
        return KulcsNyersHosszuva;
        
    }
    
    private static String kodol(String nyers, String[] kulcs, String[][] tabulaRecta){

        String[] splitNyers = nyers.split("");
        String titkositottSzoveg = "";
        
        int i, j, k;
        
        for(i = 0; i < splitNyers.length; i++){
            for(j = 0; j < tabulaRecta[0].length; j++){
                if(splitNyers[i].equals(tabulaRecta[0][j])){
                    for(k = 0; k < 70; k++){
                        if(tabulaRecta[k][0].equals(kulcs[i])){
                            titkositottSzoveg += tabulaRecta[j][k];
                        }
                    }
                }
            }
            
        }
        
        return titkositottSzoveg;
        
    }
    
    private static String dekodol(String titkositottSzoveg, String[] kulcs, String[][] tabulaRecta){
        String[] splitTitkositott = titkositottSzoveg.split("");
        String dekodoltSzoveg = "";
        int i, j, k;
        
        for(i = 0; i < kulcs.length; i++){
            for(j = 0; j < tabulaRecta.length; j++){
                if(kulcs[i].equals(tabulaRecta[j][0])){
                    for(k = 0; k < tabulaRecta[j].length; k++){
                        if(tabulaRecta[j][k].equals(splitTitkositott[i])){
                            dekodoltSzoveg += tabulaRecta[0][k];
                        }
                    }
                }
            }
        }
        
        return dekodoltSzoveg;
    }
    
    private static String mezoVizsgalat(String kulcs, String szoveg){
        
        Pattern pattern = Pattern.compile("[$&+,:;=\\\\?@#|/'<>.^ˇ~§˘°˛`˙´˝¨¸×¤*()%!-123456789ß{}đäĐ]");
        
        if(szoveg.isEmpty() || kulcs.isEmpty()){
            return "A mezők kitöltése kötelező!";
        }else if(pattern.matcher(szoveg).find() || pattern.matcher(kulcs).find() || (szoveg.contains(" ") || kulcs.contains(" "))){
            return "A mezők nem tartalmazhatnak speciális karaktereket és számokat!";
        }else{
            return "OK";
        }
        
    }
    
    public RejtjelezoFrame() {
        initComponents();
        /*for (int i = 0; i < tabulaRecta[0].length; i++) {
            for (int j = 0; j < tabulaRecta[i].length; j++) {
                System.out.print(tabulaRecta[i][j] + " ");
            }
            System.out.println();
        }*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NyersSzoveg = new javax.swing.JTextField();
        Cim = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Titkositas = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        TitkositottSzoveg = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        DekodolandoSzoveg = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Dekodolas = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        DekodoltSzoveg = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        KulcsMezo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        KulcsDekodMezo = new javax.swing.JTextField();
        HibaUzenet = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Cim.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Cim.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Cim.setText("Vigenère-rejtjelező");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Adja meg a titkosítani kívánt szöveget");

        Titkositas.setText("Titkosítás");
        Titkositas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TitkositasActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Titkosított szöveg");

        TitkositottSzoveg.setEditable(false);
        TitkositottSzoveg.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Kódoló");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Dekódoló");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Adja meg a dekódolni kívánt szöveget");

        Dekodolas.setText("Dekódolás");
        Dekodolas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DekodolasActionPerformed(evt);
            }
        });

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Dekódolt szöveg");

        DekodoltSzoveg.setEditable(false);
        DekodoltSzoveg.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Adja meg a titkosításhoz szükséges kulcsot");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Adja meg a dekódoláshoz szükséges kulcsot");

        HibaUzenet.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        HibaUzenet.setForeground(new java.awt.Color(204, 0, 0));
        HibaUzenet.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Cim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(KulcsMezo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                            .addComponent(NyersSzoveg, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Titkositas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TitkositottSzoveg, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                            .addComponent(Dekodolas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DekodoltSzoveg)
                            .addComponent(DekodolandoSzoveg)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(KulcsDekodMezo)))
                    .addComponent(HibaUzenet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Cim)
                .addGap(18, 18, 18)
                .addComponent(HibaUzenet)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(KulcsMezo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(KulcsDekodMezo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NyersSzoveg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DekodolandoSzoveg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Titkositas)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TitkositottSzoveg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Dekodolas)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DekodoltSzoveg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TitkositasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TitkositasActionPerformed
        
        HibaUzenet.setText("");
        
        kulcs = KulcsMezo.getText().trim();
        nyers = NyersSzoveg.getText().trim();
        
        vizsgalatEredmeny = mezoVizsgalat(nyers, kulcs);
        
        if(vizsgalatEredmeny != "OK"){
            HibaUzenet.setText(vizsgalatEredmeny);
        }else{      
            String titkositottSzoveg;

            titkositottSzoveg = kodol(nyers, kulcsSzovegHosszuvaTetele(nyers, kulcs), tabulaRecta);
            TitkositottSzoveg.setText(titkositottSzoveg);
        }
        
    }//GEN-LAST:event_TitkositasActionPerformed

    private void DekodolasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DekodolasActionPerformed
        
        HibaUzenet.setText("");
        
        kulcs = KulcsDekodMezo.getText().trim();
        nyers = DekodolandoSzoveg.getText().trim();
        
        vizsgalatEredmeny = mezoVizsgalat(nyers, kulcs);
        
        if(vizsgalatEredmeny != "OK"){
            HibaUzenet.setText(vizsgalatEredmeny);
        }else{
            String dekodolt;

            dekodolt = dekodol(nyers, kulcsSzovegHosszuvaTetele(nyers, kulcs), tabulaRecta);

            DekodoltSzoveg.setText(dekodolt);
        }
        
    }//GEN-LAST:event_DekodolasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RejtjelezoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RejtjelezoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RejtjelezoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RejtjelezoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RejtjelezoFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cim;
    private javax.swing.JTextField DekodolandoSzoveg;
    private javax.swing.JButton Dekodolas;
    private javax.swing.JTextField DekodoltSzoveg;
    private javax.swing.JLabel HibaUzenet;
    private javax.swing.JTextField KulcsDekodMezo;
    private javax.swing.JTextField KulcsMezo;
    private javax.swing.JTextField NyersSzoveg;
    private javax.swing.JButton Titkositas;
    private javax.swing.JTextField TitkositottSzoveg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
